import CoarseDeGiorgiAudit.Solution.WeakHarnackLpLq
import CoarseDeGiorgiAudit.Solution.BridgeChallengeLp
import CoarseDeGiorgiAudit.Solution.BridgeChallengeUniform
import CoarseDeGiorgiAudit.Solution.BridgeChallengeLocalLp
